modLoader="javafml" #mandatory
loaderVersion="[37,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"
issueTrackerURL="https://github.com/fallOut015/bucket_of_chicken/issues" #optional
[[mods]] #mandatory
modId="bucket_of_chicken" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Bucket of Chicken" #mandatory
updateJSONURL="https://raw.githubusercontent.com/fallOut015/bucket_of_chicken/main/src/main/resources/updates.json" #optional
displayURL="https://www.curseforge.com/minecraft/mc-mods/bucket-of-chicken" #optional
logoFile="bucket_of_chicken.png" #optional
credits="Thanks for this mod goes to chickens" #optional
authors="fallOut015" #optional
description='''
Chicken
'''
[[dependencies.bucket_of_chicken]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[37,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.bucket_of_chicken]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1,1.18)"
    ordering="NONE"
    side="BOTH"
